apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: npn/client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: npn/post
      context: posts
      sync:
        manual:
          - src: "*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infa/k8s/*
deploy:
  kubectl: {}
